### PR TITLE
compiler: Avoid generating unnecessary conditionals

### PR DESCRIPTION
**Pull request by FabioLuporini**

### CODE REVIEW

**Review by mloubout — APPROVED** [review]
GTG. Is there a basic example/test for it or is it for some non trivial case?

**Review by georgebisbas — APPROVED** [review]
Agree with Mathias for a test, otherwise GTG

**Comment by FabioLuporini** [comment]
I thought I had responded, but my comment not showing up? 
Anyway...

> or is it for some non trivial case?

The opposite -- this tiny patch is just for super trivial cases and as I said it's just about the aesthetics of the generated code, to avoid generating uselss

```
if (true)
```

**Comment by FabioLuporini** [comment]
I thought I had responded, but my comment not showing up? 
Anyway...

> or is it for some non trivial case?

The opposite -- this tiny patch is just for super trivial cases and as I said it's just about the aesthetics of the generated code, to avoid generating uselss

```
if (true)
```

**Pull request merged**
