### PR TITLE
WIP: Adding tests for benchmark.py

### PR DESCRIPTION
**Pull request by georgebisbas**
Trying to revive the benchmark testing.\
Comments from the old PR
https://github.com/devitocodes/devito/pull/957

### CODE REVIEW

**Comment by FabioLuporini** [comment]
why is this a PR already?

**Comment by georgebisbas** [comment]
> why is this a PR already?

No it is not ready. Do you mind if I keep it open for short-term? Like 24 hours?

**Comment by FabioLuporini** [comment]
sure np....but out of curiosity, why?

**Comment by georgebisbas** [comment]
> sure np....but out of curiosity, why?

Because I am thinking of pushing my changes to see how they react on travis.
I can run pytest locally but can I do something similar for travis?

**Comment by FabioLuporini** [comment]
travis always runs even w/o PRs

it's azure pipelines that runs only when a PR is open

**Comment by georgebisbas** [comment]
> travis always runs even w/o PRs
> 
> it's azure pipelines that runs only when a PR is open

Correct. You have told me that again in the past but I forgot.
I will close temporarily.

**Pull request closed without merging**
