### PR TITLE
GitHub Action to publish to pypi

### PR DESCRIPTION
**Pull request by navjotk**

### CODE REVIEW

**Comment by mloubout** [comment]
LGTM

**Comment by FabioLuporini** [comment]
> We may want to publish 4.0 too by hand too in case

agreed

**Comment by FabioLuporini** [comment]
LGTM.

Dumb question: where/when can we see this on pipy?

**Comment by navjotk** [comment]
First release after merging this should trigger a publish to pypi, so after that?

**Comment by FabioLuporini** [comment]
shall we merge this?

**Comment by mloubout** [comment]
Yes, but I'd rather merge pytest first then just force merge this one (smaller) than the opposite :D

**Pull request merged**
