### PR TITLE
Add cython and versioneer to requirements.txt

### PR DESCRIPTION
**Pull request by jkwashbourne**
Add cython and versioneer so `pip install` works without errors

### CODE REVIEW

**Comment by jkwashbourne** [comment]
pyrevolve install fails. 
if you first install cython and versioneer pyrevolve install.

**Comment by mloubout** [comment]
That's quite odd, I've install it from scratch in multiple docker images that have nothing and it installs fine. What version of python and such is it?

**Comment by jkwashbourne** [comment]
@mloubout  `Python 3.6.10` 

Might be due to our conda install from inside julia (via adding our Devito.jl package). 

But `conda` and `versioneer` seem to be requirements for pyrevolve, correct? Maybe the issue is that `pyrevolve` only has `flake8` in `requirements.txt`

**Comment by jkwashbourne** [comment]
moved to pyrevolve

**Pull request closed without merging**
