### PR TITLE
Tutorials: add shift parameter to Ren visco-acoustic equation

### PR DESCRIPTION
**Pull request by nogueirapeterson**

### CODE REVIEW

**Comment by mloubout** [comment]
Shouldn't it be added to the `operator.py` in the examples as well?

**Comment by nogueirapeterson** [comment]
> Shouldn't it be added to the `operator.py` in the examples as well?

Yes, it should. But I added to the `operator.py` in the other PR (#1567).

**Review by georgebisbas — COMMENTED** [review]
Has the shift parameter been also added to the codebase in examples? If not, should it be added? I just want to make sure that this addition reflects to the `examples/...` and not only in the notebook. Thanks!

**Comment by nogueirapeterson** [comment]
> Has the shift parameter been also added to the codebase in examples? If not, should it be added? I just want to make sure that this addition reflects to the `examples/...` and not only in the notebook. Thanks!

Hi George
 I added the shift parameter in the codebase too. But I did it in the PR (#1567).

**Review by georgebisbas — APPROVED** [review]

**Comment by FabioLuporini** [comment]
LGTM. @mloubout ?

**Pull request merged**
