### PR TITLE
Moved from PGI to HPC SDK.  New NVIDIA Based-Container.

### PR DESCRIPTION
**Pull request by kenhester**
Uses the latest HPC SDK.

### CODE REVIEW

**Comment by mloubout** [comment]
Looks great thanks. Is MPI working correctly inside this image? I know I had issues with the previous one.

**Comment by kenhester** [comment]
> Looks great thanks. Is MPI working correctly inside this image? I know I had issues with the previous one.

I did not test MPI. Looks like the Examples-mpi  task passed.  Should I still test independently?

**Comment by mloubout** [comment]
>. Should I still test independently?

It's ok, I'll try it when I get time.

**Review by FabioLuporini — APPROVED** [review]

**Comment by FabioLuporini** [comment]
Looks good, thanks!

**Comment by FabioLuporini** [comment]
Merged, thanks!

**Pull request merged**
