### PR TITLE
Created pytest core for mac

### PR DESCRIPTION
**Pull request by BlockSprintZIf**
Based on mloubout's test install branch

### CODE REVIEW

**Comment by navjotk** [comment]
Depends on 1068 so merge that before this.

**Comment by mloubout** [comment]
yask does not support OS X so remove that one, not sure about ops (@FabioLuporini)

You probably don't need a new yaml file but you can add cases to the existing `pytest-core`

**Comment by FabioLuporini** [comment]
> not sure about ops 

ops is fine for now as there is no actual offloading (yet)

**Comment by FabioLuporini** [comment]
> You probably don't need a new yaml file but you can add cases to the existing pytest-core

agreed

**Comment by FabioLuporini** [comment]
@navjotk @mloubout @ggorman : do we actually need to run tests on the mac build ? isn't it not just enough to check the installation ? perhaps run `test_operator` only ? 

I think running the entire test suite is overkill

**Comment by mloubout** [comment]
>I think running the entire test suite is overkill

I agree, only thing needed on OSX is to make sure it's installed and compiler works with it so a single test should be fine.

**Pull request merged**
