### PR TITLE
Examples: fix GemPy notebook import failures

### PR DESCRIPTION
**Pull request by EdCaunt**

### CODE REVIEW

**Comment by FabioLuporini** [comment]
any updates here?

**Comment by EdCaunt** [comment]
Have chased the GemPy guys but nothing yet

**Comment by FabioLuporini** [comment]
any news from gempy

**Comment by EdCaunt** [comment]
> any news from gempy

Still waiting on a new version. Have poked them again to get some kind of timeline for when we can expect that. The alternative would be to install GemPy from their latest master (since it's been fixed there for a while), but I'm not keen on that personally.

**Comment by georgebisbas** [comment]
GemPY prepapred a pre-release

https://github.com/cgre-aachen/gempy/releases/tag/2023.2.0

**Comment by FabioLuporini** [comment]
closing as superseded by #2320

**Pull request closed without merging**
