### PR TITLE
gpu: Blocking for GPU offloading

### PR DESCRIPTION
**Pull request by italoaug**
This PR aims to enable tiling in GPUs codes both with OpenMP and OpenACC.

### CODE REVIEW

**Review by FabioLuporini — COMMENTED** [review]
@italoaug looking good

We need tests that make explicit use of blocking though

You could parametrize `test_gpu_openmp.py::test_iso_acoustic` over `blocklevels=None` (default, == `blocklevels=0`) and `blocklevels=1`

Same with OpenACC? it should work with it too

So it may be functionally working but, at least with OpenACC, we'll need two layers of parallelism (based on my experimentation) to make it effective. One level of parallelism for the thread blocks, and one for the warps inside the thread blocks

OpenACC example:

```
      #pragma acc loop collapse(3)
      for (int x0_blk0 = x_m; x0_blk0 <= x_M; x0_blk0 += 16)
      {
        for (int y0_blk0 = y_m; y0_blk0 <= y_M; y0_blk0 += 4)
        {
          for (int z0_blk0 = z_m; z0_blk0 <= z_M; z0_blk0 += 32)
          {
            #pragma acc loop collapse(3)
            for (int x = x0_blk0; x <= x0_blk0 + 15; x += 1)
            {
              for (int y = y0_blk0; y <= y0_blk0 + 3; y += 1)
              {
                for (int z = z0_blk0; z <= z0_blk0 + 31; z += 1)
```

if you enable blocklevels=1 on openmp and/or openacc but the performance sucks (ie, systematically worse than no blocking), then we should wait to land this PR until we have one that addresses it completely

**Review by georgebisbas — CHANGES_REQUESTED** [review]
So with OpenACC i am getting:
```
  #pragma acc parallel loop collapse(3) present(damp,u,vp)
  for (int x0_blk0 = x_m; x0_blk0 <= x_M; x0_blk0 += x0_blk0_size)
  {
    for (int y0_blk0 = y_m; y0_blk0 <= y_M; y0_blk0 += y0_blk0_size)
    {
      for (int z0_blk0 = z_m; z0_blk0 <= z_M; z0_blk0 += z0_blk0_size)
      {
        for (int x = x0_blk0; x <= x0_blk0 + x0_blk0_size - 1; x += 1)
        {
          for (int y = y0_blk0; y <= y0_blk0 + y0_blk0_size - 1; y += 1)
          {
            for (int z = z0_blk0; z <= z0_blk0 + z0_blk0_size - 1; z += 1)
            {
              float r19 = 1.0/(vp[x + 4][y + 4][z + 4]*vp[x + 4][y + 4][z + 4]);
              u[t2][x + 4][y + 4][z + 4] = (r19*(-r4*(-2.0F*u[t0][x + 4][y + 4][z + 4]) - r4*u[t1][x + 4][y + 4][z + 4]) + r5*damp[x + 1][y + 1][z + 1]*u[t0][x + 4][y + 4][z + 4] - 3.70370379e-4F*(u[t0][x + 2][y + 4][z + 4] + u[t0][x + 4][y + 2][z + 4] + u[t0][x + 4][y + 4][z + 2] + u[t0][x + 4][y + 4][z + 6] + u[t0][x + 4][y + 6][z + 4] + u[t0][x + 6][y + 4][z + 4]) + 5.92592607e-3F*(u[t0][x + 3][y + 4][z + 4] + u[t0][x + 4][y + 3][z + 4] + u[t0][x + 4][y + 4][z + 3] + u[t0][x + 4][y + 4][z + 5] + u[t0][x + 4][y + 5][z + 4] + u[t0][x + 5][y + 4][z + 4]) - 3.33333341e-2F*u[t0][x + 4][y + 4][z + 4])/(r19*r4 + r5*damp[x + 1][y + 1][z + 1]);
            }
          }
        }
      }
    }
  }
}

```

and compilation error:
```
hostptr=0x7fff86bd8000,stride=1,size=114244,extent=-114244,eltsize=4,name=damp,flags=0x200=present,async=-1,threadid=1
Present table dump for device[1]: NVIDIA Tesla GPU 0, compute capability 6.0, threadid=1
host:0x555557f32000 device:0x7fff629ba200 size:12 presentcount:0+1 line:56 name:src_coords
host:0x555558134000 device:0x7fff629ba000 size:268 presentcount:0+1 line:56 name:src
host:0x5555585b6000 device:0x7fff628fa000 size:786432 presentcount:0+1 line:56 name:rec_coords
host:0x7fff16d22000 device:0x7ffef8000000 size:488491008 presentcount:0+1 line:56 name:u
host:0x7fff3e3b5000 device:0x7fff34000000 size:162830336 presentcount:0+1 line:56 name:vp
host:0x7fffb1838000 device:0x7fff62c00000 size:17563648 presentcount:0+1 line:56 name:rec
allocated block device:0x7ffef8000000 size:488491008 thread:1
allocated block device:0x7fff34000000 size:162830336 thread:1
allocated block device:0x7fff628fa000 size:786432 thread:1
allocated block device:0x7fff629ba000 size:512 thread:1
allocated block device:0x7fff629ba200 size:512 thread:1
allocated block device:0x7fff62c00000 size:17563648 thread:1
deleted block   device:0x7fff4c000000 size:154458112 threadid=1 
FATAL ERROR: data in PRESENT clause was not found on device 1: name=damp host:0x7fff86bd8000

```

**Review by georgebisbas — COMMENTED** [review]
Is it ready for me to give it another go at gpus? 
What about adding some tests regarding blocking, similar to what test_dle.py has?
e.g.  `test_cache_blocking_structure` ?
If I am not mistaken, current tests only check correctness (e.g. norms) and not codegen.

**Comment by FabioLuporini** [comment]
in light of recent discussions on slack, this needs some work before being considered ready for merge

**Pull request closed without merging**
