### PR TITLE
gpu: Update to HPC SDK 21.1

### PR DESCRIPTION
**Pull request by kenhester**
Update to HPC SDK 20.11
Improved IB support

### CODE REVIEW

**Review by mloubout — APPROVED** [review]
Looks fine to me.

Stupid question probably, any reason why the versions are  AMD64?

**Comment by kenhester** [comment]
> Looks fine to me.
> 
> Stupid question probably, any reason why the versions are AMD64?

AMD invented the 64-bit x86 instruction set. Intel copied it later.

**Comment by kenhester** [comment]
Was PR accepted or do I need to resubmit?

**Review by georgebisbas — APPROVED** [review]
PR ok for me, have we actually tested on GPU-ci ? @FabioLuporini @rhodrin ?

**Pull request closed without merging**
