### PR TITLE
compiler: Improve IndexDerivative lowering

### PR DESCRIPTION
**Pull request by FabioLuporini**
Tiny enhancement to avoid useless stupid temporary variables in the generated code

### CODE REVIEW

**Comment by FabioLuporini** [comment]
"Fabio, have you thought about just performing a round of `cse()` instead"

"Yes I have, unfortunately it's not that easy because CSE is a Cluster-local pass, which doesn't work well here"

**Review by mloubout — APPROVED** [review]

**Comment by georgebisbas** [comment]
> "Fabio, have you thought about just performing a round of `cse()` instead"
> 
> "Yes I have, unfortunately it's not that easy because CSE is a Cluster-local pass, which doesn't work well here"

Why it does not work well?

**Comment by FabioLuporini** [comment]
> Why does it not work well? Not sure I understand TBH

`lower_index_derivative` might produce:

```
Cluster([
  r1 = 0
  r1 += <lowered index derivative>
  r0 = r1
])
```

CSE would be able to see that r0 is unnecessary here and safely removable. But `r0` is needed in later Clusters, so it would produce wrong code ultimately

Note that this is just a simplified example

You would need to understand `lower_index_derivatives` fully to appreciate all the different flavors of this issue

**Comment by georgebisbas** [comment]
> > Why does it not work well? Not sure I understand TBH
> 
> `lower_index_derivative` might produce:
> 
> ```
> Cluster([
>   r1 = 0
>   r1 += <lowered index derivative>
>   r0 = r1
> ])
> ```
> 
> CSE would be able to see that r0 is unnecessary here and safely removable. But `r0` is needed in later Clusters, so it would produce wrong code ultimately
> 
> Note that this is just a simplified example
> 
> You would need to understand `lower_index_derivatives` fully to appreciate all the different flavors of this issue

Thanks

**Review by georgebisbas — APPROVED** [review]

**Pull request merged**
