### PR TITLE
compiler: Fix MPI mode diag2 does not need a MPIRegion

### PR DESCRIPTION
**Pull request by mmohrhard**
`Diag2HaloExchangeBuilder` does not use or require the `MPIRegion` that the base class `Overlap2HaloExchangeBuilder` wants to create.

### CODE REVIEW

**Comment by mloubout** [comment]
Thnaks! Would you have a small test that fails without that change?

**Comment by mmohrhard** [comment]
> Thnaks! Would you have a small test that fails without that change?

Not a simple one or one that I can share. In our case it works around a bug that we are still trying to track down where the MPIRegion object fails with specific sub domain constructions.

However, unrelated to the issue this PR is fixing an inconsistency as the diag2 mode does not need the MPIRegion object.

**Review by FabioLuporini — APPROVED** [review]
As long as it passes CI, good to go

**Comment by FabioLuporini** [comment]
Merged, thanks

**Pull request merged**
