### PR TITLE
deps: Drop deprecated distutils imports

### PR DESCRIPTION
**Pull request by georgebisbas**
Had this locally (maybe from 3 months ago?)
did a minor change...PRing for a test...
If anyone wants to continue on this..feel free..

It helps to avoid all the warnings created by this:
https://peps.python.org/pep-0632/#:~:text=In%20Python%203.10%20and%203.11,platforms%20will%20not%20be%20added.

### CODE REVIEW

**Comment by mloubout** [comment]
distutils still used in `setup.py` for install though, should we change it too

**Comment by mloubout** [comment]
@georgebisbas as above we may wanna completely get rid of it i.e cyamfe the `setup.py`. Pip is moving away from distuyils anyway.

**Comment by georgebisbas** [comment]
> anyway.

My understanding is that setuptools is the first option when it comes for versioning. Where do you that distutils is used?

**Comment by mloubout** [comment]
Nevermind confused myself somehow

**Review by mloubout — APPROVED** [review]

**Review by FabioLuporini — APPROVED** [review]
Excellent. Merging

**Pull request merged**
